using UnityEngine;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using System.Runtime.Serialization;

public static class SaveSystem
{
    public static void SavePlayer (Player player)
    {
        BinaryFormatter formatter = new BinaryFormatter();
        string path = Application.persistentDataPath + "/player.fun";
      
        FileStream stream = new FileStream(path, FileMode.Create);

        PlayerData data = new PlayerData(player);

        formatter.Serialize(stream, data);
        stream.Close();
    }

    public static PlayerData LoadPlayer(Player player)
    {
        var data = new PlayerData(player);
        string path = Application.persistentDataPath + "/player.fun";
        if (File.Exists(path))
        {
            BinaryFormatter formatter = new BinaryFormatter();
            FileStream stream = new FileStream(path, FileMode.Open);

            stream.Close();
            
            /*путь 1*/
            data.PositionOfPoints_x[0,0] = -1f;
            data.PositionOfPoints_y[0, 0] = -0.5f;
            data.PositionOfPoints_z[0, 0] = -1f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0,1] = -1f;
            data.PositionOfPoints_y[0, 1] = -0.5f;
            data.PositionOfPoints_z[0, 1] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0,2] = -1f;
            data.PositionOfPoints_y[0, 2] = -0.5f;
            data.PositionOfPoints_z[0, 2] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0,3] = -2f;
            data.PositionOfPoints_y[0, 3] = -0.5f;
            data.PositionOfPoints_z[0, 3] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0,4] = -3f;
            data.PositionOfPoints_y[0, 4] = -0.5f;
            data.PositionOfPoints_z[0, 4] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0,5] = -4f;
            data.PositionOfPoints_y[0, 5] = -0.5f;
            data.PositionOfPoints_z[0, 5] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 6] = -5f;
            data.PositionOfPoints_y[0, 6] = -0.5f;
            data.PositionOfPoints_z[0, 6] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 7] = -6f;
            data.PositionOfPoints_y[0, 7] = -0.5f;
            data.PositionOfPoints_z[0, 7] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 8] = -7f;
            data.PositionOfPoints_y[0, 8] = -0.5f;
            data.PositionOfPoints_z[0, 8] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 9] = -8f;
            data.PositionOfPoints_y[0, 9] = -0.5f;
            data.PositionOfPoints_z[0, 9] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 10] = -9f;
            data.PositionOfPoints_y[0, 10] = -0.5f;
            data.PositionOfPoints_z[0, 10] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 11] = -10f;
            data.PositionOfPoints_y[0, 11] = -0.5f;
            data.PositionOfPoints_z[0, 11] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 12] = -11f;
            data.PositionOfPoints_y[0, 12] = -0.5f;
            data.PositionOfPoints_z[0, 12] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 13] = -12f;
            data.PositionOfPoints_y[0, 13] = -0.5f;
            data.PositionOfPoints_z[0, 13] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 14] = -13f;
            data.PositionOfPoints_y[0, 14] = -0.5f;
            data.PositionOfPoints_z[0, 14] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 15] = -14f;
            data.PositionOfPoints_y[0, 15] = -0.5f;
            data.PositionOfPoints_z[0, 15] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 16] = -15f;
            data.PositionOfPoints_y[0, 16] = -0.5f;
            data.PositionOfPoints_z[0, 16] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 17] = -16f;
            data.PositionOfPoints_y[0, 17] = -0.5f;
            data.PositionOfPoints_z[0, 17] = -2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 18] = -16f;
            data.PositionOfPoints_y[0, 18] = -0.5f;
            data.PositionOfPoints_z[0, 18] = -1f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 19] = -16f;
            data.PositionOfPoints_y[0, 19] = -0.5f;
            data.PositionOfPoints_z[0, 19] = 0;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 20] = -16f;
            data.PositionOfPoints_y[0, 20] = -0.5f;
            data.PositionOfPoints_z[0, 20] = 1f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 21] = -16f;
            data.PositionOfPoints_y[0, 21] = 0;
            data.PositionOfPoints_z[0, 21] = 2f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 22] = -16f;
            data.PositionOfPoints_y[0, 22] = 0;
            data.PositionOfPoints_z[0, 22] = 3f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 23] = -16f;
            data.PositionOfPoints_y[0, 23] = 0;
            data.PositionOfPoints_z[0, 23] = 4f;
            data.NumberOfWayPoint[0]++;
            data.PositionOfPoints_x[0, 24] = -16f;
            data.PositionOfPoints_y[0, 24] = 0;
            data.PositionOfPoints_z[0, 24] = 5f;
            data.NumberOfWayPoint[0]++;
            data.NumberOfWay++;
            
            /*part 2*/
            data.PositionOfPoints_x[1,0] = -1f;
            data.PositionOfPoints_y[1, 0] = -0.5f;
            data.PositionOfPoints_z[1, 0] = -1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1,1] = -1f;
            data.PositionOfPoints_y[1, 1] = -0.5f;
            data.PositionOfPoints_z[1, 1] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1,2] = -1f;
            data.PositionOfPoints_y[1, 2] = -0.5f;
            data.PositionOfPoints_z[1, 2] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1,3] = -2f;
            data.PositionOfPoints_y[1, 3] = -0.5f;
            data.PositionOfPoints_z[1, 3] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1,4] = -3f;
            data.PositionOfPoints_y[1, 4] = -0.5f;
            data.PositionOfPoints_z[1, 4] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1,5] = -4f;
            data.PositionOfPoints_y[1, 5] = -0.5f;
            data.PositionOfPoints_z[1, 5] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 6] = -5f;
            data.PositionOfPoints_y[1, 6] = -0.5f;
            data.PositionOfPoints_z[1, 6] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 7] = -6f;
            data.PositionOfPoints_y[1, 7] = -0.5f;
            data.PositionOfPoints_z[1, 7] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 8] = -7f;
            data.PositionOfPoints_y[1, 8] = -0.5f;
            data.PositionOfPoints_z[1, 8] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 9] = -8f;
            data.PositionOfPoints_y[1, 9] = -0.5f;
            data.PositionOfPoints_z[1, 9] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 10] = -9f;
            data.PositionOfPoints_y[1, 10] = -0.5f;
            data.PositionOfPoints_z[1, 10] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 11] = -10f;
            data.PositionOfPoints_y[1, 11] = -0.5f;
            data.PositionOfPoints_z[1, 11] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 12] = -11f;
            data.PositionOfPoints_y[1, 12] = -0.5f;
            data.PositionOfPoints_z[1, 12] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 13] = -12f;
            data.PositionOfPoints_y[1, 13] = -0.5f;
            data.PositionOfPoints_z[1, 13] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 14] = -13f;
            data.PositionOfPoints_y[1, 14] = -0.5f;
            data.PositionOfPoints_z[1, 14] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 15] = -14f;
            data.PositionOfPoints_y[1, 15] = -0.5f;
            data.PositionOfPoints_z[1, 15] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 16] = -15f;
            data.PositionOfPoints_y[1, 16] = -0.5f;
            data.PositionOfPoints_z[1, 16] = -2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 17] = -16f;
            data.PositionOfPoints_y[1, 17] = -0.5f;
            data.PositionOfPoints_z[1, 17] = -2f;
            data.NumberOfWayPoint[1]++;
            
            data.PositionOfPoints_x[1, 18] = -16f;
            data.PositionOfPoints_y[1, 18] = -0.5f;
            data.PositionOfPoints_z[1, 18] = -1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 19] = -16f;
            data.PositionOfPoints_y[1, 19] = -0.5f;
            data.PositionOfPoints_z[1, 19] = 0;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 20] = -16f;
            data.PositionOfPoints_y[1, 20] = 0;
            data.PositionOfPoints_z[1, 20] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 21] = -16f;
            data.PositionOfPoints_y[1, 21] = 0;
            data.PositionOfPoints_z[1, 21] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 22] = -16f;
            data.PositionOfPoints_y[1, 22] = 0;
            data.PositionOfPoints_z[1, 22] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 23] = -17f;
            data.PositionOfPoints_y[1, 23] = 0;
            data.PositionOfPoints_z[1, 23] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 24] = -18f;
            data.PositionOfPoints_y[1, 24] = 0;
            data.PositionOfPoints_z[1, 24] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 25] = -19f;
            data.PositionOfPoints_y[1, 25] = 0;
            data.PositionOfPoints_z[1, 25] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 26] = -20f;
            data.PositionOfPoints_y[1, 26] = 0;
            data.PositionOfPoints_z[1, 26] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 27] = -21f;
            data.PositionOfPoints_y[1, 27] = 0;
            data.PositionOfPoints_z[1, 27] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 28] = -22f;
            data.PositionOfPoints_y[1, 28] = 0;
            data.PositionOfPoints_z[1, 28] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 29] = -23f;
            data.PositionOfPoints_y[1, 29] = 0;
            data.PositionOfPoints_z[1, 29] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 30] = -24f;
            data.PositionOfPoints_y[1, 30] = 0;
            data.PositionOfPoints_z[1, 30] = 1f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 31] = -25f;
            data.PositionOfPoints_y[1, 31] = 0;
            data.PositionOfPoints_z[1, 31] = 1f;
            data.NumberOfWayPoint[1]++;
            
            data.PositionOfPoints_x[1, 32] = -26f;
            data.PositionOfPoints_y[1, 32] = 0;
            data.PositionOfPoints_z[1, 32] = 2f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 33] = -26f;
            data.PositionOfPoints_y[1, 33] = 0;
            data.PositionOfPoints_z[1, 33] = 3f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 34] = -26f;
            data.PositionOfPoints_y[1, 34] = 0;
            data.PositionOfPoints_z[1, 34] = 4f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 35] = -26f;
            data.PositionOfPoints_y[1, 35] = 0;
            data.PositionOfPoints_z[1, 35] = 5f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 36] = -26f;
            data.PositionOfPoints_y[1, 36] = 0;
            data.PositionOfPoints_z[1, 36] = 6f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 37] = -26f;
            data.PositionOfPoints_y[1, 37] = 0;
            data.PositionOfPoints_z[1, 37] = 7f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 38] = -26f;
            data.PositionOfPoints_y[1, 38] = 0;
            data.PositionOfPoints_z[1, 38] = 8f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 39] = -26f;
            data.PositionOfPoints_y[1, 39] = 0;
            data.PositionOfPoints_z[1, 39] = 9f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 40] = -26f;
            data.PositionOfPoints_y[1, 40] = 0;
            data.PositionOfPoints_z[1, 40] = 10f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 41] = -26f;
            data.PositionOfPoints_y[1, 41] = 0;
            data.PositionOfPoints_z[1, 41] = 11f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 42] = -26f;
            data.PositionOfPoints_y[1, 42] = 0;
            data.PositionOfPoints_z[1, 42] = 12f;
            data.NumberOfWayPoint[1]++;
            
            data.PositionOfPoints_x[1, 43] = -26f;
            data.PositionOfPoints_y[1, 43] = -1f;
            data.PositionOfPoints_z[1, 43] = 13f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 44] = -26f;
            data.PositionOfPoints_y[1, 44] = -1.5f;
            data.PositionOfPoints_z[1, 44] = 14f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 45] = -26f;
            data.PositionOfPoints_y[1, 45] = -1.5f;
            data.PositionOfPoints_z[1, 45] = 15f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 46] = -26f;
            data.PositionOfPoints_y[1, 46] = -1.5f;
            data.PositionOfPoints_z[1, 46] = 16f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 47] = -26f;
            data.PositionOfPoints_y[1, 47] = -1.5f;
            data.PositionOfPoints_z[1, 47] = 17f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 48] = -26f;
            data.PositionOfPoints_y[1, 48] = -1.5f;
            data.PositionOfPoints_z[1, 48] = 18f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 49] = -26f;
            data.PositionOfPoints_y[1, 49] = -1.5f;
            data.PositionOfPoints_z[1, 49] = 19f;
            data.NumberOfWayPoint[1]++;
            data.PositionOfPoints_x[1, 50] = -27f;
            data.PositionOfPoints_y[1, 50] = -1.5f;
            data.PositionOfPoints_z[1, 50] = 20f;
            data.NumberOfWayPoint[1]++;
            data.NumberOfWay++;
            
            /*part 3*/
            
            /*data.PositionOfPoints_x[fff,0] = -1f;
            data.PositionOfPoints_y[fff, 0] = -0.5f;
            data.PositionOfPoints_z[fff, 0] = -1f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff,1] = -1f;
            data.PositionOfPoints_y[fff, 1] = -0.5f;
            data.PositionOfPoints_z[fff, 1] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff,2] = -1f;
            data.PositionOfPoints_y[fff, 2] = -0.5f;
            data.PositionOfPoints_z[fff, 2] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff,3] = -2f;
            data.PositionOfPoints_y[fff, 3] = -0.5f;
            data.PositionOfPoints_z[fff, 3] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff,4] = -3f;
            data.PositionOfPoints_y[fff, 4] = -0.5f;
            data.PositionOfPoints_z[fff, 4] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff,5] = -4f;
            data.PositionOfPoints_y[fff, 5] = -0.5f;
            data.PositionOfPoints_z[fff, 5] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 6] = -5f;
            data.PositionOfPoints_y[fff, 6] = -0.5f;
            data.PositionOfPoints_z[fff, 6] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 7] = -6f;
            data.PositionOfPoints_y[fff, 7] = -0.5f;
            data.PositionOfPoints_z[fff, 7] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 8] = -7f;
            data.PositionOfPoints_y[fff, 8] = -0.5f;
            data.PositionOfPoints_z[fff, 8] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 9] = -8f;
            data.PositionOfPoints_y[fff, 9] = -0.5f;
            data.PositionOfPoints_z[fff, 9] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 10] = -9f;
            data.PositionOfPoints_y[fff, 10] = -0.5f;
            data.PositionOfPoints_z[fff, 10] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 11] = -10f;
            data.PositionOfPoints_y[fff, 11] = -0.5f;
            data.PositionOfPoints_z[fff, 11] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 12] = -11f;
            data.PositionOfPoints_y[fff, 12] = -0.5f;
            data.PositionOfPoints_z[fff, 12] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 13] = -12f;
            data.PositionOfPoints_y[fff, 13] = -0.5f;
            data.PositionOfPoints_z[fff, 13] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 14] = -13f;
            data.PositionOfPoints_y[fff, 14] = -0.5f;
            data.PositionOfPoints_z[fff, 14] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 15] = -14f;
            data.PositionOfPoints_y[fff, 15] = -0.5f;
            data.PositionOfPoints_z[fff, 15] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 16] = -15f;
            data.PositionOfPoints_y[fff, 16] = -0.5f;
            data.PositionOfPoints_z[fff, 16] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 17] = -16f;
            data.PositionOfPoints_y[fff, 17] = -0.5f;
            data.PositionOfPoints_z[fff, 17] = -2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 18] = -16f;
            data.PositionOfPoints_y[fff, 18] = -0.5f;
            data.PositionOfPoints_z[fff, 18] = -1f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 19] = -16f;
            data.PositionOfPoints_y[fff, 19] = -0.5f;
            data.PositionOfPoints_z[fff, 19] = 0;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 20] = -16f;
            data.PositionOfPoints_y[fff, 20] = -0.5f;
            data.PositionOfPoints_z[fff, 20] = 1f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 21] = -16f;
            data.PositionOfPoints_y[fff, 21] = 0;
            data.PositionOfPoints_z[fff, 21] = 2f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 22] = -16f;
            data.PositionOfPoints_y[fff, 22] = 0;
            data.PositionOfPoints_z[fff, 22] = 3f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 23] = -16f;
            data.PositionOfPoints_y[fff, 23] = 0;
            data.PositionOfPoints_z[fff, 23] = 4f;
            data.NumberOfWayPoint[fff]++;
            data.PositionOfPoints_x[fff, 24] = -16f;
            data.PositionOfPoints_y[fff, 24] = 0;
            data.PositionOfPoints_z[fff, 24] = 5f;
            data.NumberOfWayPoint[fff]++;
            data.NumberOfWay++;*/
            
            //path 3
            
            data.PositionOfPoints_x[2,0] = -1f;
            data.PositionOfPoints_y[2, 0] = -0.5f;
            data.PositionOfPoints_z[2, 0] = -1f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2,1] = -1f;
            data.PositionOfPoints_y[2, 1] = -0.5f;
            data.PositionOfPoints_z[2, 1] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2,2] = -1f;
            data.PositionOfPoints_y[2, 2] = -0.5f;
            data.PositionOfPoints_z[2, 2] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2,3] = -2f;
            data.PositionOfPoints_y[2, 3] = -0.5f;
            data.PositionOfPoints_z[2, 3] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2,4] = -3f;
            data.PositionOfPoints_y[2, 4] = -0.5f;
            data.PositionOfPoints_z[2, 4] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2,5] = -4f;
            data.PositionOfPoints_y[2, 5] = -0.5f;
            data.PositionOfPoints_z[2, 5] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 6] = -5f;
            data.PositionOfPoints_y[2, 6] = -0.5f;
            data.PositionOfPoints_z[2, 6] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 7] = -6f;
            data.PositionOfPoints_y[2, 7] = -0.5f;
            data.PositionOfPoints_z[2, 7] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 8] = -7f;
            data.PositionOfPoints_y[2, 8] = -0.5f;
            data.PositionOfPoints_z[2, 8] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 9] = -8f;
            data.PositionOfPoints_y[2, 9] = -0.5f;
            data.PositionOfPoints_z[2, 9] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 10] = -9f;
            data.PositionOfPoints_y[2, 10] = -0.5f;
            data.PositionOfPoints_z[2, 10] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 11] = -10f;
            data.PositionOfPoints_y[2, 11] = -0.5f;
            data.PositionOfPoints_z[2, 11] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 12] = -11f;
            data.PositionOfPoints_y[2, 12] = -0.5f;
            data.PositionOfPoints_z[2, 12] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 13] = -12f;
            data.PositionOfPoints_y[2, 13] = -0.5f;
            data.PositionOfPoints_z[2, 13] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 14] = -13f;
            data.PositionOfPoints_y[2, 14] = -0.5f;
            data.PositionOfPoints_z[2, 14] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 15] = -14f;
            data.PositionOfPoints_y[2, 15] = -0.5f;
            data.PositionOfPoints_z[2, 15] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 16] = -15f;
            data.PositionOfPoints_y[2, 16] = -0.5f;
            data.PositionOfPoints_z[2, 16] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 17] = -16f;
            data.PositionOfPoints_y[2, 17] = -0.5f;
            data.PositionOfPoints_z[2, 17] = -2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 18] = -16f;
            data.PositionOfPoints_y[2, 18] = -0.5f;
            data.PositionOfPoints_z[2, 18] = -1f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 19] = -16f;
            data.PositionOfPoints_y[2, 19] = -0.5f;
            data.PositionOfPoints_z[2, 19] = 0;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 20] = -16f;
            data.PositionOfPoints_y[2, 20] = -0.5f;
            data.PositionOfPoints_z[2, 20] = 1f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 21] = -16f;
            data.PositionOfPoints_y[2, 21] = 0;
            data.PositionOfPoints_z[2, 21] = 2f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 22] = -16f;
            data.PositionOfPoints_y[2, 22] = 0;
            data.PositionOfPoints_z[2, 22] = 3f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 23] = -16f;
            data.PositionOfPoints_y[2, 23] = 0;
            data.PositionOfPoints_z[2, 23] = 4f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 24] = -16f;
            data.PositionOfPoints_y[2, 24] = 0;
            data.PositionOfPoints_z[2, 24] = 5f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 25] = -15f;
            data.PositionOfPoints_y[2, 25] = 0;
            data.PositionOfPoints_z[2, 25] = 5f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 26] = -14f;
            data.PositionOfPoints_y[2, 26] = 0;
            data.PositionOfPoints_z[2, 26] = 5f;
            data.NumberOfWayPoint[2]++;
            data.PositionOfPoints_x[2, 27] = -13f;
            data.PositionOfPoints_y[2, 27] = 0;
            data.PositionOfPoints_z[2, 27] = 5f;
            data.NumberOfWayPoint[2]++;
            data.NumberOfWay++;
            
            
            // part 4
            data.PositionOfPoints_x[3,0] = -1f;
            data.PositionOfPoints_y[3, 0] = -0.5f;
            data.PositionOfPoints_z[3, 0] = -1f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3,1] = -1f;
            data.PositionOfPoints_y[3, 1] = -0.5f;
            data.PositionOfPoints_z[3, 1] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3,2] = -1f;
            data.PositionOfPoints_y[3, 2] = -0.5f;
            data.PositionOfPoints_z[3, 2] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3,3] = -2f;
            data.PositionOfPoints_y[3, 3] = -0.5f;
            data.PositionOfPoints_z[3, 3] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3,4] = -3f;
            data.PositionOfPoints_y[3, 4] = -0.5f;
            data.PositionOfPoints_z[3, 4] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3,5] = -4f;
            data.PositionOfPoints_y[3, 5] = -0.5f;
            data.PositionOfPoints_z[3, 5] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 6] = -5f;
            data.PositionOfPoints_y[3, 6] = -0.5f;
            data.PositionOfPoints_z[3, 6] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 7] = -6f;
            data.PositionOfPoints_y[3, 7] = -0.5f;
            data.PositionOfPoints_z[3, 7] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 8] = -7f;
            data.PositionOfPoints_y[3, 8] = -0.5f;
            data.PositionOfPoints_z[3, 8] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 9] = -8f;
            data.PositionOfPoints_y[3, 9] = -0.5f;
            data.PositionOfPoints_z[3, 9] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 10] = -9f;
            data.PositionOfPoints_y[3, 10] = -0.5f;
            data.PositionOfPoints_z[3, 10] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 11] = -10f;
            data.PositionOfPoints_y[3, 11] = -0.5f;
            data.PositionOfPoints_z[3, 11] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 12] = -11f;
            data.PositionOfPoints_y[3, 12] = -0.5f;
            data.PositionOfPoints_z[3, 12] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 13] = -12f;
            data.PositionOfPoints_y[3, 13] = -0.5f;
            data.PositionOfPoints_z[3, 13] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 14] = -13f;
            data.PositionOfPoints_y[3, 14] = -0.5f;
            data.PositionOfPoints_z[3, 14] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 15] = -14f;
            data.PositionOfPoints_y[3, 15] = -0.5f;
            data.PositionOfPoints_z[3, 15] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 16] = -15f;
            data.PositionOfPoints_y[3, 16] = -0.5f;
            data.PositionOfPoints_z[3, 16] = -2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 17] = -16f;
            data.PositionOfPoints_y[3, 17] = -0.5f;
            data.PositionOfPoints_z[3, 17] = -2f;
            data.NumberOfWayPoint[3]++;
            
             data.PositionOfPoints_x[3, 18] = -16f;
            data.PositionOfPoints_y[3, 18] = -0.5f;
            data.PositionOfPoints_z[3, 18] = -1f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 19] = -16f;
            data.PositionOfPoints_y[3, 19] = -0.5f;
            data.PositionOfPoints_z[3, 19] = 0;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 20] = -16f;
            data.PositionOfPoints_y[3, 20] = 0;
            data.PositionOfPoints_z[3, 20] = 1f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 21] = -16f;
            data.PositionOfPoints_y[3, 21] = 0;
            data.PositionOfPoints_z[3, 21] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 22] = -16f;
            data.PositionOfPoints_y[3, 22] = 0;
            data.PositionOfPoints_z[3, 22] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 23] = -17f;
            data.PositionOfPoints_y[3, 23] = 0;
            data.PositionOfPoints_z[3, 23] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 24] = -18f;
            data.PositionOfPoints_y[3, 24] = 0;
            data.PositionOfPoints_z[3, 24] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 25] = -19f;
            data.PositionOfPoints_y[3, 25] = 0;
            data.PositionOfPoints_z[3, 25] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 26] = -20f;
            data.PositionOfPoints_y[3, 26] = 0;
            data.PositionOfPoints_z[3, 26] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 27] = -21f;
            data.PositionOfPoints_y[3, 27] = 0;
            data.PositionOfPoints_z[3, 27] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 28] = -22f;
            data.PositionOfPoints_y[3, 28] = 0;
            data.PositionOfPoints_z[3, 28] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 29] = -23f;
            data.PositionOfPoints_y[3, 29] = 0;
            data.PositionOfPoints_z[3, 29] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 30] = -24f;
            data.PositionOfPoints_y[3, 30] = 0;
            data.PositionOfPoints_z[3, 30] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 31] = -25f;
            data.PositionOfPoints_y[3, 31] = 0;
            data.PositionOfPoints_z[3, 31] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 32] = -26f;
            data.PositionOfPoints_y[3, 32] = 0;
            data.PositionOfPoints_z[3, 32] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 33] = -27f;
            data.PositionOfPoints_y[3, 33] = 0;
            data.PositionOfPoints_z[3, 33] = 2f;
            data.NumberOfWayPoint[3]++;
            data.PositionOfPoints_x[3, 33] = -28f;
            data.PositionOfPoints_y[3, 33] = 0;
            data.PositionOfPoints_z[3, 33] = 2f;
            data.NumberOfWayPoint[3]++;
            data.NumberOfWay++;
            
            //part 5
            
            data.PositionOfPoints_x[4,0] = -1f;
            data.PositionOfPoints_y[4, 0] = -0.5f;
            data.PositionOfPoints_z[4, 0] = -1f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4,1] = -1f;
            data.PositionOfPoints_y[4, 1] = -0.5f;
            data.PositionOfPoints_z[4, 1] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4,2] = -1f;
            data.PositionOfPoints_y[4, 2] = -0.5f;
            data.PositionOfPoints_z[4, 2] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4,3] = -2f;
            data.PositionOfPoints_y[4, 3] = -0.5f;
            data.PositionOfPoints_z[4, 3] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4,4] = -3f;
            data.PositionOfPoints_y[4, 4] = -0.5f;
            data.PositionOfPoints_z[4, 4] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4,5] = -4f;
            data.PositionOfPoints_y[4, 5] = -0.5f;
            data.PositionOfPoints_z[4, 5] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 6] = -5f;
            data.PositionOfPoints_y[4, 6] = -0.5f;
            data.PositionOfPoints_z[4, 6] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 7] = -6f;
            data.PositionOfPoints_y[4, 7] = -0.5f;
            data.PositionOfPoints_z[4, 7] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 8] = -7f;
            data.PositionOfPoints_y[4, 8] = -0.5f;
            data.PositionOfPoints_z[4, 8] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 9] = -8f;
            data.PositionOfPoints_y[4, 9] = -0.5f;
            data.PositionOfPoints_z[4, 9] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 10] = -9f;
            data.PositionOfPoints_y[4, 10] = -0.5f;
            data.PositionOfPoints_z[4, 10] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 11] = -10f;
            data.PositionOfPoints_y[4, 11] = -0.5f;
            data.PositionOfPoints_z[4, 11] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 12] = -11f;
            data.PositionOfPoints_y[4, 12] = -0.5f;
            data.PositionOfPoints_z[4, 12] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 13] = -12f;
            data.PositionOfPoints_y[4, 13] = -0.5f;
            data.PositionOfPoints_z[4, 13] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 14] = -13f;
            data.PositionOfPoints_y[4, 14] = -0.5f;
            data.PositionOfPoints_z[4, 14] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 15] = -14f;
            data.PositionOfPoints_y[4, 15] = -0.5f;
            data.PositionOfPoints_z[4, 15] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 16] = -15f;
            data.PositionOfPoints_y[4, 16] = -0.5f;
            data.PositionOfPoints_z[4, 16] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 17] = -16f;
            data.PositionOfPoints_y[4, 17] = -0.5f;
            data.PositionOfPoints_z[4, 17] = -2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 18] = -16f;
            data.PositionOfPoints_y[4, 18] = -0.5f;
            data.PositionOfPoints_z[4, 18] = -1f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 19] = -16f;
            data.PositionOfPoints_y[4, 19] = -0.5f;
            data.PositionOfPoints_z[4, 19] = 0;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 20] = -16f;
            data.PositionOfPoints_y[4, 20] = -0.5f;
            data.PositionOfPoints_z[4, 20] = 1f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 21] = -16f;
            data.PositionOfPoints_y[4, 21] = 0;
            data.PositionOfPoints_z[4, 21] = 2f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 22] = -16f;
            data.PositionOfPoints_y[4, 22] = 0;
            data.PositionOfPoints_z[4, 22] = 3f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 23] = -16f;
            data.PositionOfPoints_y[4, 23] = 0;
            data.PositionOfPoints_z[4, 23] = 4f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 24] = -16f;
            data.PositionOfPoints_y[4, 24] = 0;
            data.PositionOfPoints_z[4, 24] = 5f;
            data.NumberOfWayPoint[4]++;
            
            data.PositionOfPoints_x[4, 25] = -15f;
            data.PositionOfPoints_y[4, 25] = 0;
            data.PositionOfPoints_z[4, 25] = 5f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 26] = -14f;
            data.PositionOfPoints_y[4, 26] = 0;
            data.PositionOfPoints_z[4, 26] = 5f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 27] = -13f;
            data.PositionOfPoints_y[4, 27] = 0;
            data.PositionOfPoints_z[4, 27] = 5f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 28] = -15f;
            data.PositionOfPoints_y[4, 28] = 0;
            data.PositionOfPoints_z[4, 28] = 5f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 29] = -14f;
            data.PositionOfPoints_y[4, 29] = 0;
            data.PositionOfPoints_z[4, 29] = 5f;
            data.NumberOfWayPoint[4]++;
            data.PositionOfPoints_x[4, 30] = -13f;
            data.PositionOfPoints_y[4, 30] = 0;
            data.PositionOfPoints_z[4, 30] = 5f;
            data.NumberOfWayPoint[4]++;
            data.NumberOfWay++;
            return data;
        }
        else
        {
            Debug.LogError("Save file is not found in " + path);
            return null;
        }
    }
}
